# Generated by Django 5.1.7 on 2025-03-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
